---
apiVersion: comcast.github.io/v1
kind: KuberhealthyCheck
metadata:
  name: node
  namespace: kuberhealthy
spec:
  runInterval: 3m
  timeout: 5m
  podSpec:
    containers:
    - name: node
      image: kuberhealthy/node-check:v0.0.8
      imagePullPolicy: Always # Change to IfNotPresent
      env:
      - name: NODE_SELECTOR
        value: "beta.kubernetes.io/instance-type=c5.4xlarge" #"dedicated=kuberhealthy" #,kubernetes.io/hostname:ip-10-112-140-38.us-west-2.compute.internal" #kops.k8s.io/instancegroup=c-nodes,beta.kubernetes.io/os=linux
      - name: DEBUG
        value: "true"
      resources:
        requests:
          cpu: 25m
          memory: 15Mi
        limits:
          cpu: 1
      restartPolicy: Never
    terminationGracePeriodSeconds: 60
