---
apiVersion: comcast.github.io/v1
kind: KuberhealthyCheck
metadata:
  name: node
  namespace: kuberhealthy
spec:
  runInterval: 3m
  timeout: 120m
  podSpec:
    containers:
    - name: node
      image: kuberhealthy/node-check:v0.0.63
      imagePullPolicy: Always # Change to IfNotPresent
      env:
      # - name: NODE_SELECTOR
      #   value: "beta.kubernetes.io/instance-type=c5.4xlarge" #"dedicated=kuberhealthy" #,kubernetes.io/hostname:ip-10-112-140-38.us-west-2.compute.internal" #kops.k8s.io/instancegroup=c-nodes,beta.kubernetes.io/os=linux
      - name: CHECK_WORKER_INTERLUDE
        value: "10"
      - name: DEBUG
        value: "true"
      resources:
        requests:
          cpu: 50m
          memory: 50Mi
        limits:
          cpu: 1
      restartPolicy: Never
    serviceAccountName: node-sa
    terminationGracePeriodSeconds: 60
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-sa
  namespace: kuberhealthy
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: node-check-rb
  namespace: kuberhealthy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: node-check-role
subjects:
  - kind: ServiceAccount
    name: node-sa
    namespace: kuberhealthy
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: node-check-role
  namespace: kuberhealthy
rules:
  - apiGroups:
      - ""
    resources:
      - "nodes"
      - "pods"
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
