---
apiVersion: comcast.github.io/v1
kind: KuberhealthyCheck
metadata:
  name: deployment
  namespace: kuberhealthy
spec:
  runInterval: 10m
  timeout: 15m
  podSpec:
    containers:
      - name: deployment
<<<<<<< HEAD
        image: kuberhealthy/deployment-check:v1.9.0
=======
        image: kuberhealthy/deployment-check:v1.8.2
>>>>>>> 5e7fbe7eebfd06d6330cfd4c599a29acaad66b34
        imagePullPolicy: IfNotPresent
        env:
          - name: CHECK_DEPLOYMENT_REPLICAS
            value: "4"
          - name: CHECK_DEPLOYMENT_ROLLING_UPDATE
            value: "true"
        resources:
          requests:
            cpu: 25m
            memory: 15Mi
          limits:
            cpu: 1
<<<<<<< HEAD
    restartPolicy: Never
=======
        restartPolicy: Never
>>>>>>> 5e7fbe7eebfd06d6330cfd4c599a29acaad66b34
    serviceAccountName: deployment-sa
    terminationGracePeriodSeconds: 60
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-check-rb
  namespace: kuberhealthy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: deployment-service-role
subjects:
  - kind: ServiceAccount
    name: deployment-sa
    namespace: kuberhealthy
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployment-service-role
  namespace: kuberhealthy
rules:
  - apiGroups:
      - "apps"
    resources:
      - deployments
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployment-sa
  namespace: kuberhealthy
