apiVersion: comcast.github.io/v1
kind: KuberhealthyCheck
metadata:
  name: dns-status-external
  namespace: kuberhealthy
spec:
  runInterval: 2m
  timeout: 15m
  podSpec:
    containers:
      - env:
          - name: HOSTNAME
            value: "google.com"
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
<<<<<<< HEAD
        image: kuberhealthy/dns-resolution-check:v1.5.0
=======
        image: kuberhealthy/dns-resolution-check:v1.4.4
>>>>>>> 5e7fbe7eebfd06d6330cfd4c599a29acaad66b34
        imagePullPolicy: IfNotPresent
        name: main
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
