---
apiVersion: comcast.github.io/v1
kind: KuberhealthyCheck
metadata:
  name: image-pull-check
  namespace: kuberhealthy
spec:
  podSpec:
    containers:
      - env:
          - name: REPORT_FAILURE
            value: "false"
          - name: REPORT_DELAY
            value: "1s"
        # test-external-check image must be uploaded to the repository you wish to test on, and below URL must be updated to match.
<<<<<<< HEAD
        image: kuberhealthy/test-external-check:v1.4.0
=======
        image: kuberhealthy/test-external-check:v1.3.3
>>>>>>> 5e7fbe7eebfd06d6330cfd4c599a29acaad66b34
        imagePullPolicy: Always
        name: main
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
  runInterval: 10m
  timeout: 1m
